### ISSUE TITLE
Passing options

### ISSUE THREAD

**Issue by JackDunnNZ** [JackDunnNZ/NL.jl#2]
There seem to be multiple ways that solvers take options for solving:

- Bonmin, Couenne and Ipopt all accept a limited subset of options at the command line, and require the writing of an [options file](http://www.coin-or.org/Ipopt/documentation/node34.html) to set most options. This file must be in the current working directory when the solver is invoked (note this isn't necessarily the directory containing the solver executable, nor the directory with the .nl file)
- I had a look at SNOPT after it was requested, and it takes all options on the command line.

I haven't yet looked at any other solvers, are there other major ones that might take options in a different way?

This suggests we need some logic that figures out what to do with the options we get passed. An additional option that triggers writing an options file? A lookup table for the solvers? Something else entirely?

Another consideration is that the options files must be named based on the solver eg. `ipopt.opt`. Currently the solver is run using the command passed in the first argument to NLSolver, but that's a pretty fragile way to detect which solver we are using. Thoughts?

cc @mlubin @tkelman @IainNZ @joehuchette

**Comment by mlubin** [comment]
How does AMPL handle this? They definitely don't use lookup tables.

**Comment by JackDunnNZ** [comment]
From the Ipopt page:

    To see which options are available through AMPL, you can run the AMPL solver executable with the ``-='' flag from the command prompt

Looks like they only allow setting the subset of parameters supported by the command line options. Probably a good option then

**Comment by tkelman** [comment]
I think they write .opt files, but I'm not positive. We should probably pick a canonical default location to be writing the .nl files to anyway to avoid littering people's filesystems too much.

**Comment by tkelman** [comment]
We could also ask @vitaut, he is watching the repository and he'll probably answer...

**Comment by vitaut** [comment]
Normally AMPL solvers receive solver options via command line or `<solver>_options` environment variable. Or what was the question? =)

**Comment by tkelman** [comment]
That was the question, thanks. So all options go via command line with AMPL.

**Comment by JackDunnNZ** [comment]
Okay, I'll just pass them through to the command line, which then clears up this question. Thanks @vitaut !

**Comment by JackDunnNZ** [comment]
There are a lot of options with `.` in the name (probably more than half of the options) e.g. `bonmin.allowable_gap`

Is there a way options like these can be set in the kwargs? If just try the following I get an error that the keyword arg is not a symbol:

    NLSolver("bonmin", bonmin.allowable_gap=0.01)

**Comment by tkelman** [comment]
Keyword arguments in the standard syntax have to be valid identifiers. You can maybe fake kwargs with non-standard symbols, but I think just using a `Dict{ASCIIString, Any}` would be better. That's what I had to do for OSoL options.

**Comment by mlubin** [comment]
Yeah, keyword arguments are the convention in MPB, but taking a dictionary instead is perfectly fine, just a bit more hassle for users.
